### ISSUE TITLE
[Windows 11] Topgrade uses Sudo when run as administrator

### ISSUE THREAD

**Issue by GideonBear** [topgrade-rs/topgrade#1025]
## I want to suggest some general feature
In Windows 11, Topgrade should not use Sudo when run as administrator, but run the command directly.

## More information
In Windows 10 running as administrator worked fine, but in Windows 11 I have to press "Yes" on Sudo's prompt multiple times (Windows Update, Microsoft Store). In Windows 10 some steps would simply fail if not run as administrator, but this is no better.

**Comment by SteveLauC** [comment]
Emm, I am no Windows expert, so I try to mirror my UNIX knowledge here.

If `sudo` is needed, shouldn't Topgrade use it? I see "press "Yes" on Sudo's prompt" as a necessary step to make `sudo` work. On Linux, sudo privilege will be [cached](https://unix.stackexchange.com/q/77356/498440), wouldn't Windows sudo handle that?

**Comment by GideonBear** [comment]
> Emm, I am no Windows expert, so I try to mirror my UNIX knowledge here.
> 
> If `sudo` is needed, shouldn't Topgrade use it? I see "press "Yes" on Sudo's prompt" as a necessary step to make `sudo` work. On Linux, sudo privilege will be [cached](https://unix.stackexchange.com/q/77356/498440), wouldn't Windows sudo handle that?

I don't see why Sudo is needed when Topgrade itself is ran as administrator, as it can just spawn processes with administrator permissions. What mostly confuses me is that Topgrade seemed to be supposed to be run as Administrator in Windows 10 (as that was the only way to get (IIRC) Windows Update to work), but in Windows 11 suddenly uses Sudo regardless of privilege state.
Anyway referencing #1015 as well (although that's on Linux), I think this behavior is unacceptable, regardless of the method to solve it. Winget installers sometimes ask me to press "Yes" as well, but that is more of a Winget problem and not really an issue; but having to do it every time, even when nothing is upgraded, is just annoying, and requires me to monitor my Topgrade run constantly.
Please don't interpret my “unacceptable” negatively though, I understand that you're not developing this for Windows primarily, and I still think Topgrade is an amazing tool, even (maybe even especially) on Windows :)

The best solution / optimal outcome that I can think of (both for Linux and Windows) is to support both running as root/administrator and running unprivileged. Then in the case of a privileged run, it should be able to run fully unattended (and hopefully still be able to upgrade tools that are not supposed to be run privileged, maybe by then switching back to the original user?), and when run unprivileged, it can sudo (and in the case of Linux, cache it).

Just throwing ideas here, lmk what you think!

**Comment by GideonBear** [comment]
Also no, Windows Sudo does no caching at all (by default anyway). I had to set it to "Inline" in the developer settings to properly work, and mirror what I saw in Windows 10 the best.

**Comment by SteveLauC** [comment]
> I don't see why Sudo is needed when Topgrade itself is ran as administrator,

Sorry for missing that `administrator` mode, it feels indeed unnecessary to use `sudo` in that case.

So, under the administrator mode, `sudo something` still requires manual verification? To me, the intuitive behavior will be that verification will be skipped, I expect Windows sudo to handle this automatically. 🫠

**Comment by GideonBear** [comment]
> > I don't see why Sudo is needed when Topgrade itself is ran as administrator,
> 
> Sorry for missing that `administrator` mode, it feels indeed unnecessary to use `sudo` in that case.
> 
> So, under the administrator mode, `sudo something` still requires manual verification? To me, the intuitive behavior will be that verification will be skipped, I expect Windows sudo to handle this automatically. 🫠

Yes, it is certainly something that I would expect Windows sudo itself to do... Unfortunately it doesn't. I can try to implement this (skipping sudo on Windows when it is administrator) myself if I have time, would that be accepted?

**Comment by SteveLauC** [comment]
> would that be accepted?

Yeah

-------

> Yes, it is certainly something that I would expect Windows sudo itself to do...

Which sudo are you using? Is it open-source? Maybe we can file an issue there if so

**Comment by GideonBear** [comment]
> > Yes, it is certainly something that I would expect Windows sudo itself to do...
> 
> Which sudo are you using? Is it open-source? Maybe we can file an issue there if so

This is the sudo that is built into Windows 11. When it is not enabled, some steps just crash with "enable sudo in the developer settings". It seems like Topgrade chooses to run sudo because it finds there is a `sudo` exe on PATH, even when `sudo` is disabled (in that case all the `sudo` exe does is crash); while in Windows 10 it was just not there. Does that seem correct?

I'm also considering looking for an alternative `sudo` implementation for Windows 11, but I'm somewhat expecting caching to be impossible on Windows...

**Comment by SteveLauC** [comment]
> This is the sudo that is built into Windows 11. 

https://github.com/microsoft/sudo this one? Could you please file an issue there(for this weird behavior)?

> but I'm somewhat expecting caching to be impossible on Windows...

Well, I hope this can be implemented. If we need to fix this within Topgrade, then all the steps that involve `sudo` need a refactor 😪


> When it is not enabled, some steps just crash with "enable sudo in the developer settings". It seems like Topgrade chooses to run sudo because it finds there is a sudo exe on PATH, even when sudo is disabled (in that case all the sudo exe does is crash); while in Windows 10 it was just not there. Does that seem correct?

Topgrade assumes as long as there is a sudo found in the `$PATH`, then it can be used. Frankly, I hate such Microsoft tricks, again, fixing this on the Topgrade side would be a big refactoring...

---------




> > I'm also considering looking for an alternative `sudo` implementation for Windows 11, but I'm somewhat expecting caching to be impossible on Windows...
> 
> https://github.com/gerardog/gsudo

Does gsudo handle the administrator mode correctly? i.e., when in the administrator mode, sudo behaves like a no-op

**Comment by GideonBear** [comment]
Relevant issue already exists:
https://github.com/microsoft/sudo/issues/1
Also: https://github.com/microsoft/sudo/issues/119
When I'm home I'll test out the "opens UAC prompt even when run as administrator" behavior and open an issue for that as well.

I agree that this is something sudo should fix themselves. I will experiment a bit with `gsudo` as well (thx for the link @soredake!)

**Comment by SteveLauC** [comment]
> It appears I made a mistake, I was not actually running it as administrator
>
> For me the issue is solved now

Good to hear!


---------

> > Can you check as well that topgrade is actually running as administrator?
>
> Yes, it is.

So under administrator mode, `sudo something` will give you a prompt?

**Comment by soredake** [comment]
> So under administrator mode, `sudo something` will give you a prompt?

No, command will just not execute when built-in sudo is disabled (which is default):

![Image](https://github.com/user-attachments/assets/6cd81f27-6008-4b28-a2b4-39d3afac7b48)

When sudo is enabled there will be no prompt when you run built-in sudo while topgrade launched with admin rights.

**Comment by SteveLauC** [comment]
> No, command will just not execute when built-in sudo is disabled (which is default):

See issue https://github.com/microsoft/sudo/issues/119, Microsoft should fix this

**Comment by SteveLauC** [comment]
> Frankly, I hate such Microsoft tricks, again, **fixing this on the Topgrade side would be a big refactoring...**


I don't want to fix it on Topgrade's side because that would change all the code that uses sudo, which is not Windows-only. So, doing this would obviously make Topgrade harder to maintain, this is my concern. If we can do it without harming that, I could possibly accept it.

Besides maintenance issues, it should really be Microsoft that fixes this issue.

**Comment by atoerien** [comment]
No clue when it changed since I use gsudo, but Windows Sudo doesn't prompt if the process is already elevated (i.e. if you ran `sudo topgrade`) anymore, and just runs the command directly, like Unix sudo does. So the problem described here shouldn't be happening anymore.

**Comment by GideonBear** [comment]
> No clue when it changed since I use gsudo, but Windows Sudo doesn't prompt if the process is already elevated (i.e. if you ran `sudo topgrade`) anymore, and just runs the command directly, like Unix sudo does. So the problem described here shouldn't be happening anymore.

I mentioned that in https://github.com/topgrade-rs/topgrade/issues/1025#issuecomment-2633879566, I should probably have changed the title.
The remaining issue now is that Windows Sudo does not cache, so multiple prompts can still appear in a single run.
That said, that's an upstream issue; I'll mark it as such but keep it open for now.

**Comment by atoerien** [comment]
Ah I missed that, my bad. Avoiding multiple prompts wouldn't be feasible for topgrade to do - the only way I can think of to do that is to elevate ourselves and then de-elevate if the command *doesn't* need sudo. But that would be super complex to implement and could still end up breaking things.

We could definitely check whether or not windows sudo is enabled though, I looked at its code and it uses a couple registry keys to store sudo "policy" on the system. I'll give that a shot after #1208 is merged.
